#!/bin/bash

# This script updates all the Virtual Machine software ie:
# omegalib
#    several modules
# bino
# Equalizer
# drishti
# [Darren 29Aug16]

# check that this script is run as root
if (( $EUID != 0 )); then
	echo "Please run $0 as root, ie. 'sudo $0'"
	exit
fi

echo "Updates omegalib and Equalizer only (WIP)"


export OMEGA_DIR=/local/omegalib

export REPOS="
omegalib
omegalib/omicron
Equalizer
"

cd /local

for REPO_NAME in $REPOS
do
	if [[ -d $REPO_NAME ]]; then
		pushd $REPO_NAME
		/usr/bin/sudo -u davm -- /usr/bin/git pull origin master
		popd
	fi
done

# omegalib submodules updated here..
cd /local/omegalib/modules
/usr/bin/sudo -u davm ./mpull

# omegalib building
cd /local/omegalib/build

# make omicron build without vrpn (WIP)
cd omicron/omicron && { /usr/bin/sudo -u davm -- cmake -DOMICRON_USE_VRPN=false . ; popd }

# set executable permissions on libraries/executables (only if successful)
/usr/bin/sudo -u davm make install && chmod -R +x $OMEGA_DIR/install/omegalib/bin/

# Equalizer
cd /local/Equalizer/build && make install

## TODO
# Bino update
# drishti update
# paraview update
# additional software

exit
