#!/bin/bash

# This script updates all the Data Arena Virtual Machine-related repositories
# [Darren 22Jan16]
#
# Added updating home directory and etc files
# [Darren 22Apr16]

# check that this script is run as root
if (( $EUID != 0 )); then
	/bin/echo "Please run $0 as root, ie. 'sudo $0'"
	exit
fi

cd

export REPOS="
examples
davm.doc
davm.movies
bin
"

cd /local

for REPO_NAME in $REPOS
do
	if [[ -d $REPO_NAME ]]; then
		pushd $REPO_NAME
		# update repositories if already there
		/usr/bin/sudo -u davm /usr/bin/git pull
		popd
	fi
done

# regenerate documentation
cd /local/davm.doc && /usr/bin/sudo -u davm /usr/bin/make html

# Update config files from home directory
cd /tmp

# do things as davm (no environment variables passed)
/usr/bin/sudo -u davm /bin/bash <<EOF

/usr/bin/git clone https://github.com/UTSDataArena/davm.user.git

# check if this symlink exists
if [[ -L /home/davm/.kde4 ]]; then
	#ZZ=`readlink -f /home/davm/.kde4`
	# move it out of the way (no env vars passed, so use directly)
	/bin/mv `readlink -f /home/davm/.kde4` /home/davm/.kde4.`date +'%y%m%d.%5N'`
fi
/usr/bin/rsync -av --chown=davm:davm davm.user/ /home/davm/

# Remove copied files
/bin/rm -rf /home/davm/.git
/bin/rm -rf /tmp/davm.user

EOF

# no longer davm. As root

# update etc files
cd /tmp
/usr/bin/git clone https://github.com/UTSDataArena/davm.etc.git
cd /tmp/davm.etc

/usr/bin/rsync -av /tmp/davm.etc/etc/ /etc/

# pull in skel files for a user?
# /usr/bin/rsync -av --chown=davm:davm /etc/skel/.bash* /home/davm/

# Remove copied files
/bin/rm -rf /tmp/davm.etc

/bin/echo "Done updating, please log out then in again"
