#!/bin/bash

# This script updates all the Virtual Machine software ie:
# omegalib
#    several modules
# bino
# Equalizer
# drishti
# [Darren 22Apr16]

# TODO:
# fetch latest release from github (or gitlab) through github API

# check that this script is run as root
if (( $EUID != 0 )); then
	echo "Please run $0 as root, ie. 'sudo $0'"
	exit
fi

echo "Not implemented yet."

exit
