#!/bin/bash

# This script updates all the Data Arena Virtual Machine-related repositories
# [Darren 22Jan16]
#
# Added updating home directory and etc files
# [Darren 22Apr16]

# check that this script is run as root
if (( $EUID != 0 )); then
	/bin/echo "Please run $0 as root, ie. 'sudo $0'"
	exit
fi

cd

GITHUB_REPO=https://github.com/UTSDataArena
GITLAB_HOST=code.research.uts.edu.au
GITLAB_REPO=git@${GITLAB_HOST}:da/DAVM

GIT_REPO=$GITLAB_REPO

# if gitlab not reachable for some reason, use github
if [[ 0 -ne `ping -c1 -W1 $GITLAB_HOST >/dev/null` ]]; then 
    GIT_REPO=$GITHUB_REPO
fi

## davm.doc removed to be replaced by wordpress updating
export REPOS="
examples
davm.movies
"

cd /local

for REPO_NAME in $REPOS
do
	if [[ -d $REPO_NAME ]]; then
		pushd $REPO_NAME
		# update repositories if already there
		/usr/bin/sudo -u davm /usr/bin/git pull
		popd
	fi
done

# update self repo as root
cd /local/bin && /usr/bin/git pull

## regenerate documentation, for previous doc system
##cd /local/davm.doc && /usr/bin/sudo -u davm /usr/bin/make html

# Update config files from home directory
cd /tmp

# do things as davm (no environment variables passed)
/usr/bin/sudo -u davm /bin/bash <<EOF

/usr/bin/git clone $GIT_REPO/davm.user.git /tmp/davm.user

# move it out of the way (no env vars passed, so use directly)

/usr/bin/rsync -bav --backup-dir="backup_$(date +%y%m%d.%5N)" --chown=davm:davm /tmp/davm.user/ /home/davm/

# Remove copied files
/bin/rm -rf /home/davm/.git
/bin/rm -rf /tmp/davm.user


EOF

# no longer davm. As root

# update etc files
cd /tmp
/usr/bin/git clone $GIT_REPO/davm.etc.git
cd /tmp/davm.etc

/usr/bin/rsync -av /tmp/davm.etc/etc/ /etc/

# pull in skel files for a user?
# /usr/bin/rsync -av --chown=davm:davm /etc/skel/.bash* /home/davm/

# Remove copied files
/bin/rm -rf /tmp/davm.etc

/bin/echo "Done updating, please log out then in again"
